version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/php-aws-codepipeline/
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu
